[build]
command = "pip install -r requirements.txt"

[start]
command = "python app.py"

[deploy]
# Specifier une tâche cron pour exécuter le script chaque minute
schedule = "* * * * *"
command = "curl -X POST https://your-railway-app-url/update_glucose"
