[build]
command = "pip install -r requirements.txt"

[start]
command = "python app.py"
command = "curl -X POST https://librelinkuptonightscout-production.up.railway.app/update_glucose"

#[deploy]
# Specifier une tâche cron pour exécuter le script chaque minute
#command = "curl -X POST https://librelinkuptonightscout-production.up.railway.app/update_glucose"
