[build]
  builder = "Nixpacks"

[deploy]
  [deploy.services]
    web = { start = "uvicorn app:app --host 0.0.0.0 --port 5000" }

  [[plugins]]
    name = "postgresql"  # Si vous avez besoin d'une base de données PostgreSQL
