[build]
command = "pip install -r requirements.txt"

[start]
command = "python app.py"

[deploy]
# Spécifier une tâche cron pour exécuter le script chaque minute
schedule = "* * * * *"
command = "curl -X POST https://librelinkuptonightscout-production.up.railway.app/update_glucose"
